In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [32]:
dataset = pd.read_csv('iris_csv.csv')
dataset.head()

sepallength 
 sepalwidth 
 petallength 
 petalwidth 
 class 
 
 
 
 
 0 
 5.1 
 3.5 
 1.4 
 0.2 
 Iris-setosa 
 
 
 1 
 4.9 
 3.0 
 1.4 
 0.2 
 Iris-setosa 
 
 
 2 
 4.7 
 3.2 
 1.3 
 0.2 
 Iris-setosa 
 
 
 3 
 4.6 
 3.1 
 1.5 
 0.2 
 Iris-setosa 
 
 
 4 
 5.0 
 3.6 
 1.4 
 0.2 
 Iris-setosa

In [33]:
X = dataset.iloc[:,1:4].values
y = dataset.iloc[:,4].values

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)

In [35]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

In [36]:
y_pred = classifier.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[12  0  0]
 [ 0  8  2]
 [ 0  0 16]]


In [38]:
from sklearn.metrics import classification_report
target_names = ['Iris-setosa','Iris-versicolor','Iris-virginica']
print(classification_report(y_test,y_pred, target_names=target_names))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.80      0.89        10
 Iris-virginica       0.89      1.00      0.94        16

       accuracy                           0.95        38
      macro avg       0.96      0.93      0.94        38
   weighted avg       0.95      0.95      0.95        38

